run:
  timeout: 3m

issues:
  max-issues-per-linter: 100
  max-same-issues: 100
  exclude:
    - "Added to album: "

linters-settings:
  gocritic:
    enabled-checks:
#      - captLocal
#      - singleCaseSwitch
#     - switchTrue
      - httpNoBody
      - emptyStringTest
      - builtinShadow
      - exposedSyncMutex
    enabled-tags:
      - diagnostic
    disabled-tags:
      - performance
      - style
      - experimental
      - opinionated

linters:
  disable-all: true
  enable:
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - misspell
    - whitespace
    - gci
    - gofmt
    - goimports
    - loggercheck
    - asasalint
    - contextcheck
    - decorder
    - dogsled
    - errchkjson
    - copyloopvar
    - ginkgolinter
    - gocheckcompilerdirectives
    - goprintffuncname
    - mirror
    - nakedret
    - gofumpt
    - stylecheck
    - unused
    - goconst
    - makezero
    - unparam
    - prealloc
    - predeclared
    - unconvert
    - unparam
    - whitespace
    - errcheck
