name: goreleaser

on:
  # label:
  #   types: created
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.23'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Set tag reference from input
      if: github.event.inputs.tag != ''
      run: |
        echo "TAG_REF=refs/tags/${{ github.event.inputs.tag}}" >> $GITHUB_ENV
        echo "TAG_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

    - name: Set tag reference from github.ref
      if: github.event.inputs.tag == ''
      run: | 
        echo "TAG_REF=${{ github.ref }}" >> $GITHUB_ENV
        echo "TAG_VERSION=${TAG_REF#refs/tags/}" >> $GITHUB_ENV
        

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ env.TAG_REF }}        

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"
      
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
        # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
