name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.23'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # goos: [linux, windows, darwin, freebsd]
        goos: [linux,windows]
        goarch: [amd64]
        # goarch: [amd64, arm64, arm]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: windows
            goarch: arm
    steps:
    - name: Set tag reference from input
      if: github.event.inputs.tag != ''
      run: |
        echo "TAG_REF=refs/tags/${{ github.event.inputs.tag}}" >> $GITHUB_ENV
        echo "TAG_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

    - name: Set tag reference from github.ref
      if: github.event.inputs.tag == ''
      run: | 
        echo "TAG_REF=${{ github.ref }}" >> $GITHUB_ENV
        echo "TAG_VERSION=${TAG_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.TAG_REF }}

    - name: Get the current commit
      id: get_commit
      run: echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Get the current date
      id: get_date
      run: echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o immich-go-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Set exec flag for Linux
      if: matrix.goos != 'windows'
      run: chmod +x immich-go-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Create archive
      run: |
        mkdir -p dist/immich-go-${{ matrix.goos }}-${{ matrix.goarch }}
        cp immich-go-${{ matrix.goos }}-${{ matrix.goarch }} dist/immich-go-${{ matrix.goos }}-${{ matrix.goarch }}/immich-go${{ matrix.goos == 'windows' && '.exe' || '' }}
        cp readme.md dist/immich-go-${{ matrix.goos }}-${{ matrix.goarch }}/
        if [ "${{ matrix.goos }}" == "windows" ]; then
          zip -r immich-go-${{ matrix.goos }}-${{ matrix.goarch }}.zip dist/immich-go-${{ matrix.goos }}-${{ matrix.goarch }}
        else
          tar -czvf immich-go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz -C dist immich-go-${{ matrix.goos }}-${{ matrix.goarch }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: immich-go-${{ matrix.goos }}-${{ matrix.goarch }}
        path: |
          ${{ matrix.goos == 'windows' && format('immich-go-{0}-{1}.zip', matrix.goos, matrix.goarch) || format('immich-go-{0}-{1}.tar.gz', matrix.goos, matrix.goarch) }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create checksums
      run: |
        checksums=$(pwd)/checksums.txt
        echo checksums = ${checksums} 
        for dir in artifacts/immich-go*; do
            pushd $dir
            md5sum *  >> ${checksums}
            popd
        done
    - name: List checksums
      run: |
        cat checksums.txt

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag || github.ref }}
        release_name: Release ${{ env.TAG_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/immich-go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        asset_name: immich-go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Assets (Windows)
      if: matrix.goos == 'windows'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/immich-go-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_name: immich-go-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_content_type: application/zip