name: Test Pipeline

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show event data
        run: |
          cat $GITHUB_EVENT_PATH
      - name: Log github.event
        run: echo "${{ toJSON(github.event) }}"   
      - name: Show the ref
        run: echo "${{ github.event.ref }}"
